<a href="https://colab.research.google.com/github/KavyaPitla-123/Task_T160600248_AIML_Workspace/blob/main/DataPreprocessing_Rainfall_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()
file_name=list(uploaded.keys())[0]
print("uploaded file:",file_name)

Saving rainfall.csv to rainfall.csv
uploaded file: rainfall.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(file_name)
df.head()

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             Rainy
1  2022-01-02       8.2         17.8      65.0         5.2             Rainy
2  2022-01-03       0.0         20.1      52.0         3.1             Sunny
3  2022-01-04       3.7         18.6      71.0         6.7             Rainy
4  2022-01-05      21.1         14.8      82.0         9.3             Rainy

In [ ]:
df.info()
df.describe()
df.isnull()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

In [ ]:
df['date'] = df['date'].astype(str).str.strip()
df['date'] = pd.to_datetime(df['date'],errors='coerce')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               53 non-null     datetime64[ns]
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 2.7+ KB

        date  rainfall  temperature  humidity  wind_speed weather_condition
0 2022-01-01      12.5         15.2      78.0         8.5             Rainy
1 2022-01-02       8.2         17.8      65.0         5.2             Rainy
2 2022-01-03       0.0         20.1      52.0         3.1             Sunny
3 2022-01-04       3.7         18.6      71.0         6.7             Rainy
4 2022-01-05      21.1         14.8      82.0         9.3             Rainy

In [ ]:
nums_cols=["rainfall","temperature","humidity","wind_speed"]
df[nums_cols]=df[nums_cols].fillna(df[nums_cols].mean())
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0])
print(df.isnull().sum())

date                 1
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

In [ ]:
df['weather_condition']=df['weather_condition'].str.lower()

df

         date   rainfall  temperature   humidity  wind_speed weather_condition
0  2022-01-01  12.500000    15.200000  78.000000    8.500000             rainy
1  2022-01-02   8.200000    17.800000  65.000000    5.200000             rainy
2  2022-01-03   0.000000    20.100000  52.000000    3.100000             sunny
3  2022-01-04   3.700000    18.600000  71.000000    6.700000             rainy
4  2022-01-05  21.100000    14.800000  82.000000    9.300000             rainy
5  2022-01-06  15.300000    16.500000  75.000000    7.800000             rainy
6  2022-01-07   6.800000    19.200000  61.000000    4.500000             rainy
7  2022-01-08   0.000000    21.700000  48.000000    2.900000             sunny
8  2022-01-09  11.200000    17.300000  73.000000    6.100000             rainy
9  2022-01-10  18.600000    15.800000  79.000000    8.900000             rainy
10 2022-01-11   9.500000    16.200000  72.000000    5.700000             rainy
11 2022-01-12   2.100000    19.800000  58.000000    3.500000             rainy
12 2022-01-13   0.000000    22.400000  45.000000    2.100000             sunny
13 2022-01-14   7.400000    17.900000  69.000000    6.500000             rainy
14 2022-01-15  14.900000    15.100000  81.000000    8.700000             rainy
15 2022-01-16  19.200000    16.800000  77.000000    7.200000             rainy
16 2022-01-17   5.600000    18.500000  63.000000    4.900000             rainy
17 2022-01-18   0.000000    21.200000  51.000000    3.300000             sunny
18 2022-01-19  10.800000    17.600000  75.000000    6.700000             rainy
19 2022-01-20  16.300000    14.500000  84.000000    9.100000             rainy
20 2022-01-21   3.900000    16.100000  71.000000    5.300000             rainy
21 2022-01-22   0.000000    19.400000  59.000000    4.100000             sunny
22 2022-01-23   7.100000    18.200000  67.000000    7.100000             rainy
23 2022-01-24  12.700000    15.700000  79.000000    8.300000             rainy
24 2022-01-25  18.400000    17.100000  76.000000    6.800000             rainy
25 2022-01-26   9.800000    19.700000  62.000000    4.700000             rainy
26 2022-01-27   0.000000    22.900000  47.000000    2.500000             sunny
27 2022-01-28   6.200000    18.500000  70.000000    7.300000             rainy
28 2022-01-29  15.500000    14.200000  83.000000    9.500000             rainy
29 2022-01-30  21.800000    16.400000  78.000000    7.600000             rainy
30 2022-01-31  11.600000    19.100000  65.000000    5.100000             rainy
31 2022-02-01   0.000000    21.600000  53.000000    3.700000             sunny
32 2022-02-02   4.300000    17.200000  73.000000    7.500000             rainy
33 2022-02-03   9.100000    15.400000  81.000000    8.900000             rainy
34 2022-02-04  17.900000    16.700000  77.000000    6.200000             rainy
35 2022-02-05   7.500000    18.900000  64.000000    4.300000             rainy
36 2022-02-06   0.000000    22.100000  49.000000    2.700000             sunny
37 2022-02-07   5.800000    17.800000  72.000000    6.900000             rainy
38 2022-02-08  13.200000    14.700000  85.000000    9.300000             rainy
39 2022-02-09  19.600000    16.200000  79.000000    7.800000             rainy
40 2022-02-10  10.400000    19.500000  66.000000    5.500000             rainy
41 2022-02-11   0.000000    23.400000  44.000000    3.100000             sunny
42 2022-02-12   6.700000    18.100000  74.000000    7.700000             rainy
43 2022-02-13  14.800000    13.900000  87.000000    9.900000             rainy
44 2022-02-14  20.500000    15.600000  81.000000    8.200000             rainy
45 2022-02-15   8.300000    19.200000  68.000000    6.100000             rainy
46 2022-02-16   0.000000    22.700000  51.000000    4.500000             sunny
47 2022-02-17   5.100000    17.400000  75.000000    8.300000             rainy
48 2022-02-18  11.900000    14.100000  89.000000   10.500000             rainy
49 2022-02-19  17.300000    15.900000  83.000000    8.600000             rainy
50 2022-02-20   9.600000    18.600000  71.000000    6.700000             rainy
51 2022-02-21   0.000000    21.300000  55.000000    5.100000             sunny
52 2022-02-22   7.400000    16.800000  77.000000    8.900000             rainy
53        NaT   9.049057    17.950943  69.245283    6.403774             rainy

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

         date   rainfall  temperature   humidity  wind_speed weather_condition
0  2022-01-01  12.500000    15.200000  78.000000    8.500000             rainy
1  2022-01-02   8.200000    17.800000  65.000000    5.200000             rainy
2  2022-01-03   0.000000    20.100000  52.000000    3.100000             sunny
3  2022-01-04   3.700000    18.600000  71.000000    6.700000             rainy
4  2022-01-05  21.100000    14.800000  82.000000    9.300000             rainy
5  2022-01-06  15.300000    16.500000  75.000000    7.800000             rainy
6  2022-01-07   6.800000    19.200000  61.000000    4.500000             rainy
7  2022-01-08   0.000000    21.700000  48.000000    2.900000             sunny
8  2022-01-09  11.200000    17.300000  73.000000    6.100000             rainy
9  2022-01-10  18.600000    15.800000  79.000000    8.900000             rainy
10 2022-01-11   9.500000    16.200000  72.000000    5.700000             rainy
11 2022-01-12   2.100000    19.800000  58.000000    3.500000             rainy
12 2022-01-13   0.000000    22.400000  45.000000    2.100000             sunny
13 2022-01-14   7.400000    17.900000  69.000000    6.500000             rainy
14 2022-01-15  14.900000    15.100000  81.000000    8.700000             rainy
15 2022-01-16  19.200000    16.800000  77.000000    7.200000             rainy
16 2022-01-17   5.600000    18.500000  63.000000    4.900000             rainy
17 2022-01-18   0.000000    21.200000  51.000000    3.300000             sunny
18 2022-01-19  10.800000    17.600000  75.000000    6.700000             rainy
19 2022-01-20  16.300000    14.500000  84.000000    9.100000             rainy
20 2022-01-21   3.900000    16.100000  71.000000    5.300000             rainy
21 2022-01-22   0.000000    19.400000  59.000000    4.100000             sunny
22 2022-01-23   7.100000    18.200000  67.000000    7.100000             rainy
23 2022-01-24  12.700000    15.700000  79.000000    8.300000             rainy
24 2022-01-25  18.400000    17.100000  76.000000    6.800000             rainy
25 2022-01-26   9.800000    19.700000  62.000000    4.700000             rainy
26 2022-01-27   0.000000    22.900000  47.000000    2.500000             sunny
27 2022-01-28   6.200000    18.500000  70.000000    7.300000             rainy
28 2022-01-29  15.500000    14.200000  83.000000    9.500000             rainy
29 2022-01-30  21.800000    16.400000  78.000000    7.600000             rainy
30 2022-01-31  11.600000    19.100000  65.000000    5.100000             rainy
31 2022-02-01   0.000000    21.600000  53.000000    3.700000             sunny
32 2022-02-02   4.300000    17.200000  73.000000    7.500000             rainy
33 2022-02-03   9.100000    15.400000  81.000000    8.900000             rainy
34 2022-02-04  17.900000    16.700000  77.000000    6.200000             rainy
35 2022-02-05   7.500000    18.900000  64.000000    4.300000             rainy
36 2022-02-06   0.000000    22.100000  49.000000    2.700000             sunny
37 2022-02-07   5.800000    17.800000  72.000000    6.900000             rainy
38 2022-02-08  13.200000    14.700000  85.000000    9.300000             rainy
39 2022-02-09  19.600000    16.200000  79.000000    7.800000             rainy
40 2022-02-10  10.400000    19.500000  66.000000    5.500000             rainy
41 2022-02-11   0.000000    23.400000  44.000000    3.100000             sunny
42 2022-02-12   6.700000    18.100000  74.000000    7.700000             rainy
43 2022-02-13  14.800000    13.900000  87.000000    9.900000             rainy
44 2022-02-14  20.500000    15.600000  81.000000    8.200000             rainy
45 2022-02-15   8.300000    19.200000  68.000000    6.100000             rainy
46 2022-02-16   0.000000    22.700000  51.000000    4.500000             sunny
47 2022-02-17   5.100000    17.400000  75.000000    8.300000             rainy
48 2022-02-18  11.900000    14.100000  89.000000   10.500000             rainy
49 2022-02-19  17.300000    15.900000  83.000000    8.600000             rainy
50 2022-02-20   9.600000    18.600000  71.000000    6.700000             rainy
51 2022-02-21   0.000000    21.300000  55.000000    5.100000             sunny
52 2022-02-22   7.400000    16.800000  77.000000    8.900000             rainy
53        NaT   9.049057    17.950943  69.245283    6.403774             rainy

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["weather_condition"] = le.fit_transform(df["weather_condition"])

print(df.head())

        date  rainfall  temperature  humidity  wind_speed  weather_condition  \
0 2022-01-01      12.5         15.2      78.0         8.5                  0
1 2022-01-02       8.2         17.8      65.0         5.2                  0
2 2022-01-03       0.0         20.1      52.0         3.1                  1
3 2022-01-04       3.7         18.6      71.0         6.7                  0
4 2022-01-05      21.1         14.8      82.0         9.3                  0

   weather_condition_encoded
0                          0
1                          0
2                          1
3                          0
4                          0

In [ ]:
df.to_csv("cleaned_rainfall.csv",index=False)

In [ ]:
df.to_excel("cleaned_rainfall.xlsx",index=False)
files.download("cleaned_rainfall.xlsx")